apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: harbor-local
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/harbor
  ref:
    tag: "24.3.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-local
  namespace: internal
spec:
  releaseName: harbor-local
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: harbor-local
    namespace: flux-system
  values:
    proxy:
      httpProxy: "http://10.70.0.45:31002"
      httpsProxy: "http://10.70.0.45:31003"
    externalURL: https://10.70.0.45:31003
    internalTLS:
      enabled: true
      caBundleSecret: "harbor-ca-bundle"
    core:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
    jobservice:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
    portal:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
    registry:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
    trivy:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
    service:
      type: NodePort
      ports:
        http: 80
        https: 443
      nodePorts:
        http: "31002"
        https: "31003"
    nginx:
      tls:
        enabled: true
        existingSecret: "harbor-tls"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-tls
  namespace: internal
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDekNDQXZPZ0F3SUJBZ0lVSzk0N3RUZHF5bld5Z0RWQldLWkkrYVdLQTlBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tNVEF1TnpBdU1DNDBOVEFlRncweU5UQXlNVEV3T0RBeU1ESmFGdzB5TmpBeQpNVEV3T0RBeU1ESmFNQlV4RXpBUkJnTlZCQU1NQ2pFd0xqY3dMakF1TkRVd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFESmdDVWdWZnVTNS85SXZSNGxNV0ErWFNVNENFY2duYzN0dGh6OFdCcUgKVUVWM0pkdXJKdktJTDF0aGJHaERwemp2UWpSSDN0MTBPZk8vSkZ0eU5mS2U3UHV3ZEZrRmd2MXZaY3Z4Mm1kVwp3U2t1eVI4UGs5UDV3UUxjN1RNSE1oOW11NWc0U0tJbUtyVjYzS3hMUVV2UGlVNmRJbGlFS1M0MFMwUXlHWU51Ck5vT0M1UG91ZVd4eUQ4Zk9mWVVlcTNQdjkzMEUzMkhSK1VROUJkeEhRQ01PU2JjM043TzhOTVV6NktsVDgrUnQKOXBBYXQzT29YZ1IydjFzWHhRMkpwN3A0czBJUGhYZTRzK2ExQmhieDJFNVdsYk92R3ZselQ5eEgvMFdtaEM4ZgpnYis3aFJPeHlucDlqNmhlRDFXSkJ3VlV2bUx6ZXlPenJWa1VURlArdmc0ajN3OEZ3VkpDOHZiYmZxdzVZYTZkCmxEQ1hWUHphNldoV0pMYkhyMGcvaTJuaEU5elc1cEQ1L054bWRBZmttcG1IKzBaUzBZY0ViRWxEOFpuczJjYzgKLy9HME0wcE5KK1dENkdUVnBmVS8xdmYzOXBTQ2h1c29oLzZoQVUvcHdkRStHdjAvVHBpdkFXT0hSdVhGSWcxUgoySWFsWWlGaGJYWjAzcGk2Sk4zSVkyc0NXWFBISVVPZEZVblFxRURFaGU1cUp3c3ZBeUFxNE1WQmRvMnVJQUNJCkUwRFh6R1FiN1RMM2VlajdmYW5xZVNrOFRxYklPQUYzMlpxOGZrN0JlZ2hLeXRsZmcxWDBkRjd2anc1QUZ6aFUKNHRBSHlLSm5xT0xoWmFpMTI2MDVsVld5MDB4VUZVYy9KMHZqaVhUUUcrRFJWV2JtdEhkYTA1bFdlWHM5R0JaaQpWd0lEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVY3FkM1pBMEZFb3cvM0Y3d3VXUitXejNIN29jd0h3WURWUjBqCkJCZ3dGb0FVY3FkM1pBMEZFb3cvM0Y3d3VXUitXejNIN29jd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FnRUFSWTVqbnRrM2NvODFJTXJNd1lhanM1U2Q3Uy9BU04yWlAxaUtaRW04dUI3dQpVV1ZOR2lrSmprRUNtbWNwTzcvMFQwRSsxN1prc1kwZis1cmoxL3VERjcrOEpkdXJXYXIwS3lNcXJMbEVlNGVtCmFudnpLMnVFQ3J2dHp0K1dBT2pLWVpHOG1xVUJqOXE2cWVNVjlCcHFyRkY0d3pSUVNaSTkrUGtxb0Q5eVBLdWsKTnFFWEV4SWtzamw4dnNyM3dzV3RTR01TcFE3ZHdsbFRIT3dOSUxhTldPQzNLYTZXY25aWEk4TkkzaC9NdWEvMApOREpQNkEzb20wZVVZNDlVN2VuWkJ0NjVSL2duNUlTbURsYUdnaUdRWUlSK01BREpDcWVSam02VHlOV0lxMEx1Ck5IOHhteWN4SVJrZ2cwdGF0RCtCbWtjdDlRY2VUZU9keEwxekYzWk9TWGlBQTI3ZG0vaERtR0xtTjhlYXhFdG0KNy9hZFVxME1BbmZaMzlPODV4Uk9jbUxGb2ZBODVNRlhnL3FSaGRxVW5XSFlHODNMWm5CWHBWRlN3Zm9JbVBLVwpxK0ZWRU1MYVhYOG1zZGhjV3lDUE5RU2JBcTBHWXkvNFNVeE9ncHFGZkZWT1BGZDB1VXR0TExRWTZQKzJRZVlHCjQ2Z0wwRm5NaXBlRU12Z3BobkJjOXV6ZEwxdWRiMlpoTlk4anl4MEttWmNMaVBXRVVYUU9sWDFqWC9JcTRBMHAKcjB5NnRKZmpvaEtHQVJNMUZ0S3cwclBKL0t0UE9pUFM1WUw2MmFRa2UxUm5xZHZidXduYldZa00xdFQrZGpRagpja2luVUdWSCtXNjd4MlI3NEtOWTh6VlpmS0pFb0krUjJzdGJFOTVkS0VFd2twdWJwY1IxeUtZNThJNmt1N1k9Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-ca-bundle
  namespace: internal
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDekNDQXZPZ0F3SUJBZ0lVSzk0N3RUZHF5bld5Z0RWQldLWkkrYVdLQTlBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tNVEF1TnpBdU1DNDBOVEFlRncweU5UQXlNVEV3T0RBeU1ESmFGdzB5TmpBeQpNVEV3T0RBeU1ESmFNQlV4RXpBUkJnTlZCQU1NQ2pFd0xqY3dMakF1TkRVd2dnSWlNQTBHQ1NxR1NJYjNEUUVBCg==