apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: "16.4.9"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-banjar-unhan-4
  namespace: banjar-unhan
spec:
  releaseName: postgresql-banjar-unhan-4
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: flux-system
  values:
    auth:
      enablePostgresUser: true
      postgresPassword: "bahan_ajar_remake"
      password: "flh0918"
      database: "bahan_ajar_remake"
    architecture: "standalone"
    image:
      tag: "12"
    containerPorts:
      postgresql: 5432
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resourcesPreset: nano
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
    tls:
      enabled: false