apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-banjar-unhan
  namespace: banjar-unhan
spec:
  releaseName: postgresql-banjar-unhan
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.4.9"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
  values:
    global:
      imageRegistry: "docker.io"
      defaultStorageClass: "standard"
      security:
        allowInsecureImages: false
      postgresql:
        auth:
          postgresPassword: "flh0918"  # Ganti dengan password yang aman
          username: "postgres"            # Opsional: custom user. Kosongkan jika tidak diperlukan.
          password: "flh0918"       # Password untuk custom user
          database: "bahan_ajar_remake"               # Nama database default
    image:
      registry: "docker.io"
      repository: "bitnami/postgresql"
      pullPolicy: "IfNotPresent"
    auth:
      enablePostgresUser: true
      postgresPassword: "bahan_ajar_remake"       # Harus sama dengan global.postgresql.auth.postgresPassword
      username: "postgres"
      password: "flh0918"
      database: "bahan_ajar_remake"
      # replicationUsername: "repl_user"
      # replicationPassword: "ChangeMeRepl123!"
    architecture: "standalone"
    containerPorts:
      postgresql: 5432
    primary:
      persistence:
        enabled: true
        storageClass: "standard"
        size: 8Gi
      resourcesPreset: nano
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
    tls:
      enabled: false