apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  url: registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "24.3.0"
  values:
    adminPassword: "Harbor12345"
    externalURL: https://harbor.wush.site
    exposureType: ingress
    ingress:
      core:
        ingressClassName: "nginx"
        hostname: harbor.wush.site
        annotations:
          external-dns.alpha.kubernetes.io/hostname: harbor.wush.site
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        extraTls:
          - hosts:
              - harbor.wush.site
            secretName: wildcard-wush-site-tls
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - harbor
            topologyKey: "kubernetes.io/hostname"
