apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: internal
spec:
  releaseName: gitlab-runner
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
        namespace: flux-system
      version: "0.73.3"
  values:
    gitlabUrl: "https://git.falahtech.com"
    rbac:
      create: true
      serviceAccountName: gitlab-runner
    runnerRegistrationToken: "glrt-j6CQ-QMH67SpfoZph7P7"
    runners:
      config: |
        concurrent = 10
        check_interval = 0
        shutdown_timeout = 0
        [session_server]
          session_timeout = 1800
        [[runners]]
          name = "gitlab-runner-k8s"
          url = "https://git.falahtech.com"
          token = "glrt-j6CQ-QMH67SpfoZph7P7"
          executor = "kubernetes"
          [runners.kubernetes]
            image = "alpine:latest"
            privileged = true
            namespace = "internal"
            poll_timeout = 600
            helper_image = "gitlab/gitlab-runner-helper:x86_64-latest"
            service_account = "gitlab-runner"
            cpu_limit = "500m"
            memory_limit = "512Mi"
            cpu_requests = "250m"
            memory_requests = "256Mi"
            dns_policy = "ClusterFirstWithHostNet"
            [runners.kubernetes.dns_config]
              nameservers = ["8.8.8.8", "1.1.1.1"]
              options = [{ name = "single-request-reopen" }]
            [runners.kubernetes.volumes]
              [[runners.kubernetes.volumes.host_path]]
                name = "docker-insecure-registries"
                mount_path = "/etc/docker/daemon.json"
                host_path = "/etc/docker/daemon.json"