apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: internal
spec:
  releaseName: gitlab-runner
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
        namespace: flux-system
      version: "0.73.3"
  values:
    runners:
      config: |
        concurrent = 1
        check_interval = 0
        shutdown_timeout = 0
        [session_server]
          session_timeout = 1800
        [[runners]]
          name = "1"
          url = "https://git.falahtech.com"
          id = 18
          token = "glrt-JuNUATJa8F9kXJ2EUzf8"
          token_obtained_at = 2025-01-16T04:52:33Z
          token_expires_at = 0001-01-01T00:00:00Z
          executor = "docker"
          [runners.custom_build_dir]
          [runners.cache]
            MaxUploadedArchiveSize = 0
            [runners.cache.s3]
            [runners.cache.gcs]
            [runners.cache.azure]
          [runners.docker]
            tls_verify = false
            image = "alpine:latest"
            privileged = true
            disable_entrypoint_overwrite = false
            oom_kill_disable = false
            disable_cache = false
            volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
