apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/harbor
  ref:
    tag: "24.3.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: internal
spec:
  releaseName: harbor-nip.io
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: harbor
    namespace: flux-system
  values:
    adminPassword: "falah0918"
    externalURL: https://container.10.70.0.45.nip.io
    exposureType: ingress
    ingress:
      core:
        ingressClassName: "nginx"
        hostname: container.10.70.0.45.nip.io
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-internal
      tls:
        - hosts:
            - container.10.70.0.45.nip.io
          secretName: container-tls
    service:
      type: ClusterIP
    portal:
      resourcesPreset: nano
    core:
      resourcesPreset: nano
    jobservice:
      resourcesPreset: nano
    registry:
      server:
        resourcesPreset: nano
      controller:
        resourcesPreset: nano
    trivy:
      resourcesPreset: nano