apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-4
  namespace: internal
spec:
  releaseName: harbor-4
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: harbor
    namespace: flux-system
  values:
    adminPassword: "falah0918"
    externalURL: https://test.10-70-0-45.sslip.io
    exposureType: ingress
    ingress:
      core:
        ingressClassName: "nginx"
        hostname: test.10-70-0-45.sslip.io
        annotations:
          acme.cert-manager.io/http01-edit-in-place: "true"
          cert-manager.io/cluster-issuer: letsencrypt-internal
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          ingress.kubernetes.io/ssl-redirect: "false"
        tls: true
        # extraTls:
        #   - hosts:
        #       - test.10-70-0-45.sslip.io
        #     secretName: wildcard-sslip-tls
    portal:
      resourcesPreset: nano
    core:
      resourcesPreset: nano
    jobservice:
      resourcesPreset: nano
    registry:
      server:
        resourcesPreset: nano
      controller:
        resourcesPreset: nano
    trivy:
      resourcesPreset: nano