apiVersion: v1
kind: ConfigMap
metadata:
  name: bahan-ajar-config
  namespace: banjar-unhan
  annotations:
    reloader.stakater.com/auto: "true"
data:
  HOST: "0.0.0.0"
  PORT: "1339"
  PUBLIC_URL: "http://127.0.0.1:1339"
  APP_KEYS: "0i1NSDM1o9J/b0hOXOchYg==,gpZ55FdO4pdWkAvfDJ04Yw==,cqWPiO5klSLPNg4ePmTTPg==,FMSYMZKHHkDmF3YAUTO6xA=="
  API_TOKEN_SALT: "qcju4lksJ02ptWJfZbX5Aw=="
  ADMIN_JWT_SECRET: "Xn0QyzF+ZAuTw9qULoQWYw=="
  TRANSFER_TOKEN_SALT: "xxKt7zi/MQDZnUFnw9b0RQ=="
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "postgresql-banjar-unhan.banjar-unhan.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "bahan_ajar_remake"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "flh0918"
  S3_REGION: "us-east-1"
  S3_ACCESS: "L3XWKlfKP39a21Cv"
  S3_SECRET: "antRVqohcUIThagJJ74dofItxIx70wKu"
  S3_ENDPOINT: "http://minio-banjar-unhan.banjar-unhan.svc.cluster.local:30011"
  S3_BUCKET: "banjar-remake"
  JWT_SECRET: "SWtIId14IRFXElKTv/SUyg=="
  SENTRY_DSN: "http://5427f74d666959482461d990baaf75de@10.70.0.30:9000/44"