apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahan-ajar-deployment
  namespace: banjar-unhan
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: bahan-ajar
    logging: "loki"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bahan-ajar
  template:
    metadata:
      labels:
        app: bahan-ajar
        logging: "loki"
      annotations:
        loki.io/scrape: "true"
        loki.io/path: "/var/log/pods/*"
        loki.io/job: "bahan-ajar"
    spec:
      containers:
        - name: bahan-ajar
          image: 10.70.0.28:4321/banjar-unhan/bahan-ajar-cms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1339
          envFrom:
            - configMapRef:
                name: bahan-ajar-config
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bahan-ajar-hpa
  namespace: banjar-unhan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bahan-ajar-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70