apiVersion: v1
kind: Service
metadata:
  name: bahan-ajar-service
  namespace: banjar-unhan
spec:
  type: NodePort
  selector:
    app: bahan-ajar
  ports:
    - protocol: TCP
      port: 1339
      targetPort: 1339
      nodePort: 31339