apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: "andrianta.321@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: internal
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: "*.10.70.0.45.nip.io"
  dnsNames:
    - "*.10.70.0.45.nip.io"
    - "10.70.0.45.nip.io"
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-manager-http01
  namespace: internal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: 10.70.0.45.nip.io
      http:
        paths:
          - path: "/.well-known/acme-challenge/"
            pathType: Prefix
            backend:
              service:
                name: cert-manager-webhook
                port:
                  number: 80