apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-internal
spec:
  acme:
    email: "andrianta.321@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    email: "andrianta.321@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-key
    solvers:
      - dns01:
          acmeDNS:
            host: ns.sslip.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-sslip
  namespace: default
spec:
  secretName: wildcard-sslip-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - "*.10-70-0-45.sslip.io"
    - "10-70-0-45.sslip.io"