apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-local
  namespace: internal
spec:
  releaseName: harbor-local
  interval: 5m
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: OCIRepository
        name: harbor
        namespace: flux-system
      version: "24.3.0"
  values:
    adminPassword: "Harbor12345"
    exposureType: nodePort
