apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/harbor
  ref:
    tag: "24.3.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-local
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "24.3.0"
  values:
    adminPassword: "Harbor12345"
    # If you want to refer to your node IP address, you can update externalURL accordingly:
    # externalURL: "http://<node-ip>:30080"
    exposureType: nodePort
    nodePorts:
      core:
        http: 30080
        https: 30443
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - harbor
            topologyKey: "kubernetes.io/hostname"
