apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/harbor
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-local
  namespace: internal
spec:
  releaseName: harbor-local
  interval: 5m
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "24.3.0"
  values:
    adminPassword: "Harbor12345"
    exposureType: nodePort
