apiVersion: v1
kind: ConfigMap
metadata:
  name: rb-lua
  namespace: internal
data:
  main.lua: |-
    local ngx = ngx

    local _M = {}

    function _M.body_filter()
      if not ngx.ctx.buffered then
        ngx.ctx.buffered = ""
      end

      local chunk = ngx.arg[1] -- Capture response body chunk
      if chunk then
        ngx.ctx.buffered = ngx.ctx.buffered .. chunk
      end

      if ngx.arg[2] then -- Last chunk of the response
        ngx.var.resp_body = string.sub(ngx.ctx.buffered, 1, 1000)
      end
    end

    return _M