kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: internal
data:
  log-format: |
    '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" "$request_body_log"';
  http-snippets: |
    log_format custom_log '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" "$request_body_log"';
    access_log /var/log/nginx/access.log custom_log;
  server-snippets: |
    lua_package_path "/usr/local/lib/lua/?.lua;;";
    lua_package_cpath "/usr/local/lib/lua/?.so;;";

    set_by_lua_block $request_body_log '
      local req_body = ngx.var.request_body
      if req_body == nil then
        return "NO BODY"
      else
        return req_body
      end
    ';
