apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-controller-config
  namespace: internal
data:
  log-format-escape-json: "true"
  log-format: |
    '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" $request_time '
    'req_body:"$request_body" resp_body:"$resp_body" '
    'req_headers:"$req_header" resp_headers:"$resp_header"'