apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      version: "2.0.1"
  values:
    controller:
      enabled: true
      electionID: "nginx-ingress-leader-election"
      service:
        type: LoadBalancer
      extraArgs:
        enable-ssl-passthrough: "true"
      configMap: "nginx-controller-config"
      volumes:
        - name: lua-plugin
          configMap:
            name: rb-lua
            defaultMode: 511
            items:
              - key: main.lua
                mode: 511
                path: main.lua
      volumeMounts:
        - mountPath: /etc/nginx/lua/plugins/rb-lua
          name: lua-plugin
      config:
        entries:
          proxy-body-size: "0"
          client-max-body-size: "0"
    enableCertManager: true
    enableExternalDNS: true
    ingressClass:
      setAsDefaultIngress: true
    admissionWebhooks:
      enabled: false
