apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: "1.8.0"
  values:
    persistence:
      defaultClass: true   # Set Longhorn as default StorageClass
      # reclaimPolicy: Retain # Keep volumes even if PVC is deleted
      allowVolumeExpansion: true
    defaultSettings:
      defaultReplicaCount: 1
      backupTarget: ""
      storageOverProvisioningPercentage: 200 # Optimize storage use
      storageMinimalAvailablePercentage: 5  # Prevent low-disk issues
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      defaultDataPath: "/var/lib/longhorn"  # Store Longhorn volumes locally
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
