apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crd
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "1.4.0"
  values:
    gatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "34.4.0"
  values:
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--api.insecure=true"
    service:
      additionalServices:
        internal:
          type: ClusterIP
          labels:
            traefik-service-label: internal
    ports:
      traefik:
        expose:
          default: false
          internal: true
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth-secret
  namespace: internal
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: falah0918
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
  namespace: internal
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: internal
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: internal-traefik-dashboard-auth@kubernetescrd
spec:
  rules:
    - host: traefik.10-70-0-45.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-internal
                port:
                  number: 8080
