apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crd
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "1.4.0"
  values:
    gatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "34.4.0"
  values:
    ingressRoute:
      dashboard:
        enabled: false
    additionalArguments:
    - "--api.insecure=true"
  extraObjects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: traefik-api
      spec:
        type: ClusterIP
        selector:
          app.kubernetes.io/name: traefik
          app.kubernetes.io/instance: traefik-default
        ports:
        - port: 8080
          name: traefik
          targetPort: 8080
          protocol: TCP
    - apiVersion: v1
      kind: Secret
      metadata:
        name: traefik-dashboard-auth-secret
      type: kubernetes.io/basic-auth
      stringData:
        username: admin
        password: falah0918
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: traefik-dashboard-auth
      spec:
        basicAuth:
          secret: traefik-dashboard-auth-secret
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: traefik-dashboard
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: default-traefik-dashboard-auth@kubernetescrd
      spec:
        rules:
        - host: traefik.10-70-0-45.sslip.io
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: traefik-api
                  port:
                    name: traefik