apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: "2.47.0"
  values:
    # proxy:
    #   type: NodePort
    env:
      log_level: debug
      nginx_http_log_format:
        valueFrom:
          configMapKeyRef:  
            key: upstream
            name: kong-external-format-config