apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: 2.47.0
  values:
    plugins:
      configMaps:
      - pluginName: file-log-capture-body
        name: file-log-capture-body
    env:
      NGINX_HTTP_LOG_FORMAT: >-
        show_everything $remote_addr - $remote_user [$time_local] "$request" $status
        $body_bytes_sent "$http_referer" "$http_user_agent" "$request_body"