apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: harbor-local
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/harbor
  ref:
    tag: "24.3.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-local
  namespace: internal
spec:
  releaseName: harbor-local-1
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: harbor-local
    namespace: flux-system
  values:
    proxy:
      httpProxy: "https://registry.falahtech.com"
    externalURL: https://registry.falahtech.com
    adminPassword: "falah0918"
    exposureType: proxy
    service:
      type: NodePort
      ports:
        http: 80
        https: 443
      nodePorts:
        http: "31000"
        https: "31000"
    nginx:
      tls:
        enabled: false
      resourcesPreset: nano
    portal:
      resourcesPreset: nano
    core:
      resourcesPreset: nano
    jobservice:
      resourcesPreset: nano
    registry:
      relativeurls: true
      server:
        resourcesPreset: nano
      controller:
        resourcesPreset: nano
    trivy:
      resourcesPreset: nano
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: longhorn
          size: 50Gi