apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/wussh/flux-new.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 10m
  path: "./releases/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  wait: true
  timeout: 3m
