apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 10m
  path: "./releases"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  wait: true
  timeout: 3m
