apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx
      version: "2.0.0"
  values:
    controller:
      enabled: true
      electionID: "nginx-ingress-leader-election"
      service:
        type: LoadBalancer
      config:
        entries:
          proxy-body-size: "0"
          client-max-body-size: "0"
      extraArgs:
        default-ssl-certificate: "internal/wildcard-wush-site-tls"
    enableCertManager: true
    enableExternalDNS: true
    ingressClass:
      setAsDefaultIngress: true