# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: cert-manager
#   namespace: flux-system
# spec:
#   interval: 10m
#   url: https://charts.jetstack.io
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: cert-manager
#   namespace: internal
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: cert-manager
#       sourceRef:
#         kind: HelmRepository
#         name: cert-manager
#         namespace: flux-system
#       version: "1.16.2"
#   values:
#     crds:
#       enabled: true
