apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: internal
spec:
  releaseName: promtail
  interval: 5m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.16.6"
  values:
    nameOverride: "promtail"
    daemonset:
      enabled: true
      autoscaling:
        enabled: false
    deployment:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    defaultVolumes:
      - name: run
        hostPath:
          path: /run/promtail
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods
    defaultVolumeMounts:
      - name: run
        mountPath: /run/promtail
      - name: containers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true
    config:
      enabled: true
      logLevel: info
      logFormat: logfmt
      serverPort: 3101
      clients:
        - url: http://loki-gateway.internal.svc.cluster.local:80/loki/api/v1/push
      positions:
        filename: /run/promtail/positions.yaml
      snippets:
        pipelineStages:
          - cri: {}
        common:
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
      file: |
        server:
          log_level: {{ .Values.config.logLevel }}
          log_format: {{ .Values.config.logFormat }}
          http_listen_port: {{ .Values.config.serverPort }}
        clients:
          {{- toYaml .Values.config.clients | nindent 2 }}
        positions:
          {{- toYaml .Values.config.positions | nindent 2 }}
        scrape_configs:
          - job_name: kubernetes-pods
            pipeline_stages:
              - cri: {}
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: keep
                source_labels:
                  - __meta_kubernetes_pod_namespace
                regex: ".*"
              - source_labels:
                  - __meta_kubernetes_pod_namespace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
    serviceMonitor:
      enabled: false
    sidecar:
      configReloader:
        enabled: false
