apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: internal
spec:
  releaseName: promtail
  interval: 5m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.16.6"
  values:
    daemonset:
      enabled: false
    deployment:
      enabled: true
      replicaCount: 2
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage:
    config:
      clients:
        - url: http://loki-gateway.internal.svc.cluster.local/loki/api/v1/push
      snippets:
        extraRelabelConfigs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
    extraVolumes:
      - name: positions
        emptyDir: {}
    extraVolumeMounts:
      - name: positions
        mountPath: /run/promtail