apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://portainer.github.io/k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: internal
spec:
  interval: 5m
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      version: "1.0.59"
  values:
    persistence:
      storageClass: longhorn
    enterpriseEdition:
      enabled: true
    service:
      type: NodePort
      httpPort: 9000
      httpNodePort: 30777
#admin
#Falah1234567
#backend
#Falah0918PRGM