apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://portainer.github.io/k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      version: "latest"
  values:
    service:
      type: NodePort
      httpPort: 9000
      httpNodePort: 30777
