apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: internal
data:
  additional-scrape-configs.yaml: |
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - '10.70.0.32:9100'