apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: internal
spec:
  releaseName: prometheus
  interval: 5m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: "27.3.1"
  values:
    rbac:
      create: true
    serviceAccounts:
      server:
        create: true
    server:
      retention: "15d"
      service:
        type: NodePort
        nodePort: 30090
      extraFlags:
        - web.enable-lifecycle
      # Mount ConfigMap untuk scrape config external node exporter
      extraVolumeMounts:
        - name: external-scrape-config
          mountPath: /etc/prometheus/external
      extraVolumes:
        - name: external-scrape-config
          configMap:
            name: external-node-exporter-scrape-config
      # Override file konfigurasi utama Prometheus agar menyertakan file_sd_configs untuk external node exporter
      configPath: /etc/config/prometheus.yml
      # Konfigurasi serverFiles.prometheus.yml akan menggantikan file bawaan chart.
      serverFiles:
        prometheus.yml:
            - job_name: external-node-exporter
              file_sd_configs:
                - files:
                    - /etc/prometheus/external/*.yml
    alertmanager:
      enabled: true
      persistence:
        enabled: true
        size: 2Gi
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-pushgateway:
      enabled: false
