apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kestra
  namespace: flux-system
spec:
  interval: 10m
  url: https://helm.kestra.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kestra
  namespace: internal
spec:
  releaseName: kestra
  interval: 5m
  chart:
    spec:
      chart: kestra
      sourceRef:
        kind: HelmRepository
        name: kestra
        namespace: flux-system
      version: "0.21.3"
  values:
    deployments:
      webserver:
        enabled: false
      executor:
        enabled: false
      indexer:
        enabled: false
      scheduler:
        enabled: false
      worker:
        enabled: false
      standalone:
        enabled: true
    postgresql:
      primary:
        persistence:
          size: 2Gi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kestra-ingress
  namespace: internal
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kestra.10-70-0-45.sslip.io`)
      kind: Rule
      services:
        - name: kestra-service
          port: 8080
      middlewares:
        - name: traefik-dashboard-auth